import test from "node:test";
import assert from "node:assert/strict";
import {FORBIDDEN_TUNNEL_TRIGGER_CHANCE,artifactChanceForDig,canTriggerForbiddenTunnel,createForbiddenTunnel,markModifierRolled,modifierFor,sanitizeArtifactModifier,sanitizeForbiddenTunnel,selectFirstPath,selectSecondPath,simulateForbiddenTunnels} from "../app/forbidden-tunnel.ts";
import {readFileSync} from "node:fs";

const seq=(...n)=>{let i=0;return()=>n[i++%n.length]};
test("trigger is one percent",()=>assert.equal(FORBIDDEN_TUNNEL_TRIGGER_CHANCE,.01));
test("first chamber contains one of every reward",()=>assert.deepEqual(new Set(Object.values(createForbiddenTunnel(seq(.1,.2),"a").firstAssignments)),new Set(["x1","x2","x5"])));
test("assignment is deterministic",()=>assert.deepEqual(createForbiddenTunnel(seq(.7,.2),"a"),createForbiddenTunnel(seq(.7,.2),"a")));
test("x1 grants baseline",()=>assert.equal(modifierFor("x1")?.chance,.0005));
test("x2 grants double",()=>assert.equal(modifierFor("x2")?.chance,.001));
test("sealed retains x5",()=>assert.equal(modifierFor("sealed")?.chance,.0025));
test("deep grants fifteen percent",()=>assert.equal(modifierFor("deep")?.chance,.15));
test("modifier replaces ordinary chance",()=>assert.equal(artifactChanceForDig(modifierFor("x2")),.001));
test("consumed modifier restores canonical baseline",()=>assert.equal(artifactChanceForDig(markModifierRolled(modifierFor("x2"))),.0005));
test("marking consumption is immutable",()=>{const m=modifierFor("deep");assert.equal(m?.consumed,false);assert.equal(markModifierRolled(m)?.consumed,true)});
test("clean state is eligible",()=>assert.equal(canTriggerForbiddenTunnel({forbiddenTunnel:null,pendingArtifactModifier:null,activeTrueEncounter:null,veinDigsRemaining:0},true),true));
test("dirty transition is ineligible",()=>assert.equal(canTriggerForbiddenTunnel({forbiddenTunnel:null,pendingArtifactModifier:null,activeTrueEncounter:null,veinDigsRemaining:0},false),false));
test("active tunnel blocks trigger",()=>assert.equal(canTriggerForbiddenTunnel({forbiddenTunnel:createForbiddenTunnel(seq(.1),"a"),pendingArtifactModifier:null,activeTrueEncounter:null,veinDigsRemaining:0},true),false));
test("pending modifier blocks trigger",()=>assert.equal(canTriggerForbiddenTunnel({forbiddenTunnel:null,pendingArtifactModifier:modifierFor("x1"),activeTrueEncounter:null,veinDigsRemaining:0},true),false));
test("artifact encounter blocks trigger",()=>assert.equal(canTriggerForbiddenTunnel({forbiddenTunnel:null,pendingArtifactModifier:null,activeTrueEncounter:{},veinDigsRemaining:0},true),false));
test("vein blocks trigger",()=>assert.equal(canTriggerForbiddenTunnel({forbiddenTunnel:null,pendingArtifactModifier:null,activeTrueEncounter:null,veinDigsRemaining:1},true),false));
test("ordinary first selection resolves",()=>{const s=createForbiddenTunnel(seq(.1,.9),"a"),d=Object.entries(s.firstAssignments).find(([,v])=>v==="x1")[0];assert.equal(selectFirstPath(s,d,seq(.1)).tunnel.chamber,"resolved")});
test("x5 opens second chamber",()=>{const s=createForbiddenTunnel(seq(.1,.9),"a"),d=Object.entries(s.firstAssignments).find(([,v])=>v==="x5")[0];assert.equal(selectFirstPath(s,d,seq(.1)).tunnel.chamber,"second")});
test("second chamber has sealed and deep",()=>{const s=createForbiddenTunnel(seq(.1,.9),"a"),d=Object.entries(s.firstAssignments).find(([,v])=>v==="x5")[0],r=selectFirstPath(s,d,seq(.1));assert.deepEqual(new Set(Object.values(r.tunnel.secondAssignments)),new Set(["sealed","deep"]))});
test("second choice resolves",()=>{const s=createForbiddenTunnel(seq(.1,.9),"a"),d=Object.entries(s.firstAssignments).find(([,v])=>v==="x5")[0],r=selectFirstPath(s,d,seq(.1));assert.equal(selectSecondPath(r.tunnel,"left").tunnel.chamber,"resolved")});
test("double first input is ignored",()=>{const s=createForbiddenTunnel(seq(.1,.9),"a"),r=selectFirstPath(s,"left",seq(.1));assert.equal(selectFirstPath(r.tunnel,"right",seq(.9)).modifier,null)});
test("valid tunnel survives sanitation",()=>{const s=createForbiddenTunnel(seq(.1,.9),"a");assert.deepEqual(sanitizeForbiddenTunnel(JSON.parse(JSON.stringify(s))),s)});
test("invalid tunnel is rejected",()=>assert.equal(sanitizeForbiddenTunnel({id:"x",chamber:"first",firstAssignments:{left:"x1",middle:"x1",right:"x5"}}),null));
test("valid modifier survives sanitation",()=>assert.deepEqual(sanitizeArtifactModifier(modifierFor("deep")),modifierFor("deep")));
test("invalid modifier is rejected",()=>assert.equal(sanitizeArtifactModifier({chance:.99,source:"hack",consumed:false}),null));
test("million-run distribution matches model",()=>{const s=simulateForbiddenTunnels(1_000_000);for(const n of Object.values(s.first))assert.ok(Math.abs(n/1_000_000-1/3)<.002);assert.ok(Math.abs(s.second.deep/(s.second.deep+s.second.sealed)-.5)<.004);assert.ok(Math.abs(s.averageTunnelChance-.0259167)<.0002);assert.ok(Math.abs(s.overallBaselineRate-.00075417)<.00001)});
test("forbidden tunnel uses the dedicated cinematic passage treatment",()=>{const css=readFileSync(new URL("../app/v069.css",import.meta.url),"utf8"),layout=readFileSync(new URL("../app/layout.tsx",import.meta.url),"utf8");assert.match(layout,/import "\.\/v069\.css"/);assert.match(css,/\.tunnel-passages button:after/);assert.match(css,/\.tunnel-passages button i:before/);assert.match(css,/\.forbidden-tunnel-overlay\.chamber-second/)});
