import type { Artifact } from "./types.ts";

export const ARTIFACT_CATALOG = [
  {
    id: "blessed-chainsword",
    role: "ARTIFACT",
    name: "THE BLESSED CHAINSWORD",
    displayName: "BLESSED BY THE OMNISSIAH",
    image: "/assets/true/blessed-chainsword.png",
    cabinetText: "The machine spirit has awakened.",
    achievementId: "omnissiah",
    selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "PEON", text: "Boss… sword have engine." },
      { type: "dialogue", speaker: "SYSTEM", text: "Machine spirit dormant." },
      { type: "dialogue", speaker: "PEON", text: "Me fix.", avatarState: "proud" },
      { type: "characterAction", character: "PEON", action: "Peon oils chainsword." },
      { type: "visual", visualId: "nothing" },
      { type: "sound", soundId: "clonk" },
      { type: "sound", soundId: "clonk" },
      { type: "dialogue", speaker: "SYSTEM", text: "What are you doing?", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Blessing.", avatarState: "proud" },
      { type: "sound", soundId: "click" },
      { type: "visual", visualId: "engine-roars" },
      { type: "dialogue", speaker: "SYSTEM", text: "…acceptable.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "ME PRIEST.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "achievement", achievementId: "omnissiah" }
    ],
  },
  {
    id: "hair-gel",
    role: "ARTIFACT",
    name: "THE HAIR GEL",
    displayName: "MISHIMA-GRADE HOLD",
    image: "/assets/true/hair-gel.png",
    cabinetText: "Industrial strength.",
    achievementId: "mishima",
    selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… hair food?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Hair gel." },
      { type: "dialogue", speaker: "PEON", text: "For Peon?" },
      { type: "dialogue", speaker: "SYSTEM", text: "You don’t have enough hair.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Peon have some.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Debatable.", avatarState: "deadpan" },
      { type: "characterAction", character: "PEON", action: "Peon studies tin." },
      { type: "dialogue", speaker: "PEON", text: "Boss use?" },
      { type: "dialogue", speaker: "SYSTEM", text: "I don’t have a head.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "mishima" }
    ],
  },
  {
    id: "green-diamond",
    role: "ARTIFACT",
    name: "THE GREEN DIAMOND",
    displayName: "FREE WILL DISABLED",
    image: "/assets/true/green-diamond.png",
    cabinetText: "Sul sul.",
    achievementId: "free-will-disabled",
    selectionWeight: 1,
    setId: "cross-reality-geology",
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "PEON", text: "BOSS! IT MINERAL!", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "No.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Green mineral.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Still no.", avatarState: "deadpan" },
      { type: "visual", visualId: "green-diamond-rises" },
      { type: "characterAction", character: "PEON", action: "It floats above Peon." },
      { type: "dialogue", speaker: "PEON", text: "Boss…", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Don’t." },
      { type: "dialogue", speaker: "PEON", text: "Why rock follow Peon?", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Keep digging." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Sul sul?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Do not speak to it." },
      { type: "achievement", achievementId: "free-will-disabled" }
    ],
  },
  {
    id: "pixel-pickaxe",
    role: "ARTIFACT",
    name: "THE PIXEL PICKAXE",
    displayName: "BETTER TOOL?",
    image: "/assets/true/pixel-pickaxe.png",
    cabinetText: "Better tool?",
    achievementId: "better-tool",
    selectionWeight: 1,
    setId: "cross-reality-geology",
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "PEON", text: "Boss… pickaxe." },
      { type: "dialogue", speaker: "SYSTEM", text: "Yes." },
      { type: "dialogue", speaker: "PEON", text: "Me use?" },
      { type: "dialogue", speaker: "SYSTEM", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Why?" },
      { type: "dialogue", speaker: "SYSTEM", text: "You already have one.", avatarState: "deadpan" },
      { type: "characterAction", character: "PEON", action: "Peon looks at his pickaxe." },
      { type: "characterAction", character: "PEON", action: "Peon looks at Pixel Pickaxe." },
      { type: "dialogue", speaker: "PEON", text: "Me have two hands.", avatarState: "proud" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "SYSTEM", text: "No.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "better-tool" }
    ],
  },
  {
    id: "storm",
    role: "ARTIFACT",
    name: "STORM",
    displayName: "STORM",
    image: "/assets/true/storm.png",
    cabinetText: "One of three.",
    achievementId: "storm",
    selectionWeight: 1,
    setId: "heed-the-call",
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "PEON", text: "Boss… Tauren stuff." },
      { type: "dialogue", speaker: "SYSTEM", text: "Storm." },
      { type: "characterAction", character: "PEON", action: "Peon touches totem." },
      { type: "sound", soundId: "zap" },
      { type: "dialogue", speaker: "PEON", text: "OW!", avatarState: "angry" },
      { type: "characterAction", character: "PEON", action: "Peon recoils." },
      { type: "dialogue", speaker: "PEON", text: "STUPID SHAMAN STICK.", avatarState: "angry" },
      { type: "achievement", achievementId: "storm" }
    ],
  },
  {
    id: "earth",
    role: "ARTIFACT",
    name: "EARTH",
    displayName: "EARTH",
    image: "/assets/true/earth.png",
    cabinetText: "One of three.",
    achievementId: "earth",
    selectionWeight: 1,
    setId: "heed-the-call",
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "PEON", text: "Boss… stuck." },
      { type: "dialogue", speaker: "SYSTEM", text: "Earth." },
      { type: "characterAction", character: "PEON", action: "Peon yanks." },
      { type: "dialogue", speaker: "PEON", text: "LET GO.", avatarState: "angry" },
      { type: "characterAction", character: "PEON", action: "Peon yanks harder." },
      { type: "dialogue", speaker: "SYSTEM", text: "You are arguing with the ground.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "GROUND STARTED.", avatarState: "angry" },
      { type: "characterAction", character: "PEON", action: "Peon yanks again." },
      { type: "dialogue", speaker: "PEON", text: "STUPID SHAMAN.", avatarState: "angry" },
      { type: "achievement", achievementId: "earth" }
    ],
  },
  {
    id: "fire",
    role: "ARTIFACT",
    name: "FIRE",
    displayName: "FIRE",
    image: "/assets/true/fire.png",
    cabinetText: "One of three.",
    achievementId: "fire",
    selectionWeight: 1,
    setId: "heed-the-call",
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "SYSTEM", text: "Fire." },
      { type: "characterAction", character: "PEON", action: "Peon stares at flames." },
      { type: "characterAction", character: "PEON", action: "Peon slowly puts hand into fire." },
      { type: "sound", soundId: "ssss" },
      { type: "dialogue", speaker: "PEON", text: "OW!", avatarState: "angry" },
      { type: "characterAction", character: "PEON", action: "Peon pulls hand back." },
      { type: "dialogue", speaker: "PEON", text: "STUPID SHAMAN FLAME.", avatarState: "angry" },
      { type: "dialogue", speaker: "SYSTEM", text: "You started it this time.", avatarState: "deadpan" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "ME HATE TRUTH.", avatarState: "angry" },
      { type: "achievement", achievementId: "fire" }
    ],
  },
  {
    id: "broken-whip",
    role: "ARTIFACT",
    name: "BROKEN WHIP",
    displayName: "FURY",
    image: "/assets/true/broken-whip.png",
    cabinetText: "Its anger survived its owner.",
    achievementId: "fury",
    selectionWeight: 1,
    setId: "nephilim-lives",
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "SYSTEM", text: "Apocalyptic weapon detected." },
      { type: "dialogue", speaker: "PEON", text: "Boss… angry rope." },
      { type: "dialogue", speaker: "SYSTEM", text: "Sister Fury." },
      { type: "visual", visualId: "the-chain-twitches" },
      { type: "characterAction", character: "PEON", action: "Peon backs away." },
      { type: "dialogue", speaker: "PEON", text: "Me no touch angry sister rope.", avatarState: "scared" },
      { type: "achievement", achievementId: "fury" }
    ],
  },
  {
    id: "spent-cylinder",
    role: "ARTIFACT",
    name: "SPENT CYLINDER",
    displayName: "STRIFE",
    image: "/assets/true/spent-cylinder.png",
    cabinetText: "Whatever it was shooting at required all of them.",
    achievementId: "strife",
    selectionWeight: 1,
    setId: "nephilim-lives",
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "SYSTEM", text: "Apocalyptic weapon detected." },
      { type: "dialogue", speaker: "PEON", text: "Boss… many bullets." },
      { type: "dialogue", speaker: "SYSTEM", text: "Brother Strife." },
      { type: "characterAction", character: "PEON", action: "Peon picks up one of the spent rounds." },
      { type: "dialogue", speaker: "PEON", text: "BIG BOOMSTICK.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Yes." },
      { type: "dialogue", speaker: "PEON", text: "HUNTER NEED?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Hunters always need.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "strife" }
    ],
  },
  {
    id: "shattered-greatsword",
    role: "ARTIFACT",
    name: "SHATTERED GREATSWORD",
    displayName: "WAR",
    image: "/assets/true/shattered-greatsword.png",
    cabinetText: "",
    achievementId: "war",
    selectionWeight: 1,
    setId: "nephilim-lives",
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "characterAction", character: "PEON", action: "Peon struggles to pull the sword free." },
      { type: "visual", visualId: "the-sword-crashes-down" },
      { type: "sound", soundId: "boom" },
      { type: "dialogue", speaker: "SYSTEM", text: "…War." },
      { type: "dialogue", speaker: "PEON", text: "ME FIGHT HUMAN?!?!", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Leave the sword alone." },
      { type: "achievement", achievementId: "war" }
    ],
  },
  {
    id: "chipped-scythe",
    role: "ARTIFACT",
    name: "CHIPPED SCYTHE",
    displayName: "DEATH",
    image: "/assets/true/chipped-scythe.png",
    cabinetText: "",
    achievementId: "death",
    selectionWeight: 1,
    setId: "nephilim-lives",
    discoverySequence: [
      { type: "visual", visualId: "the-scythe-slides-free" },
      { type: "visual", visualId: "ambient-sound-fades" },
      { type: "dialogue", speaker: "SYSTEM", text: "Unmaker weapon detected." },
      { type: "dialogue", speaker: "PEON", text: "Boss???", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "Do. Not. Touch. That.", avatarState: "angry" },
      { type: "characterAction", character: "PEON", action: "Peon backs away." },
      { type: "dialogue", speaker: "PEON", text: "Me no want white angel.", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Wise.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "death" }
    ],
  },
  {
    id: "m16",
    role: "ARTIFACT",
    name: "M16",
    displayName: "THE COUNTER SIDE",
    image: "/assets/true/m16.png",
    cabinetText: "One side of an argument nobody has finished.",
    achievementId: "counter-side",
    selectionWeight: 1,
    setId: "choose-a-side",
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "PEON", text: "Boss… boomstick." },
      { type: "dialogue", speaker: "SYSTEM", text: "M16." },
      { type: "characterAction", character: "PEON", action: "Peon examines rifle." },
      { type: "dialogue", speaker: "PEON", text: "Good boomstick?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Yes." },
      { type: "dialogue", speaker: "PEON", text: "Peon keep?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Then bad boomstick.", avatarState: "angry" },
      { type: "achievement", achievementId: "counter-side" }
    ],
  },
  {
    id: "ak-47",
    role: "ARTIFACT",
    name: "AK-47",
    displayName: "ONE SIDE",
    image: "/assets/true/ak-47.png",
    cabinetText: "",
    achievementId: "one-side-of-the-argument",
    selectionWeight: 1,
    setId: "choose-a-side",
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "PEON", text: "Boss… boomstick." },
      { type: "dialogue", speaker: "SYSTEM", text: "AK-47 FOR EVERYONE!", avatarState: "panic" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Me get two?", avatarState: "proud" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "SYSTEM", text: "Keep digging.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "one-side-of-the-argument" }
    ],
  },
  {
    id: "yellow-ninja-mask",
    role: "ARTIFACT",
    name: "YELLOW NINJA MASK",
    displayName: "DISCO INFERNO",
    image: "/assets/true/yellow-ninja-mask.png",
    cabinetText: "",
    achievementId: "disco-inferno",
    selectionWeight: 1,
    setId: "finish-him",
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "PEON", text: "Boss… why rogue yellow." },
      { type: "dialogue", speaker: "FOREMAN", text: "That’s not a rogue." },
      { type: "dialogue", speaker: "PEON", text: "Why rogue fire?" },
      { type: "dialogue", speaker: "FOREMAN", text: "IT IS NOT A ROGUE.", avatarState: "angry" },
      { type: "dialogue", speaker: "PEON", text: "Me know rogue.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Get back to digging.", avatarState: "angry" },
      { type: "achievement", achievementId: "disco-inferno" }
    ],
  },
  {
    id: "blue-ninja-mask",
    role: "ARTIFACT",
    name: "BLUE NINJA MASK",
    displayName: "FROZEN FROZEN INFANT",
    image: "/assets/true/blue-ninja-mask.png",
    cabinetText: "",
    achievementId: "frozen-frozen-infant",
    selectionWeight: 1,
    setId: "finish-him",
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "PEON", text: "Boss…" },
      { type: "dialogue", speaker: "FOREMAN", text: "IT IS NOT A ROGUE.", avatarState: "angry" },
      { type: "dialogue", speaker: "PEON", text: "It rogue.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "I swear, one more time.", avatarState: "angry" },
      { type: "dialogue", speaker: "PEON", text: "Me hate rogue.", avatarState: "angry" },
      { type: "dialogue", speaker: "FOREMAN", text: "Most do." },
      { type: "achievement", achievementId: "frozen-frozen-infant" }
    ],
  },
  {
    id: "wrong-ore",
    role: "ARTIFACT",
    name: "THE WRONG ORE",
    displayName: "WRONG MINE",
    image: "/assets/true/wrong-ore.png",
    cabinetText: "Valuable somewhere else.",
    achievementId: "wrong-mine",
    selectionWeight: 1,
    setId: "cross-reality-geology",
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "PEON", text: "Boss… ore?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Yes." },
      { type: "dialogue", speaker: "PEON", text: "Add ore?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Wrong mine." },
      { type: "dialogue", speaker: "PEON", text: "Ore is ore.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Incompatible ore detected." },
      { type: "dialogue", speaker: "PEON", text: "Stupid ore.", avatarState: "angry" },
      { type: "achievement", achievementId: "wrong-mine" }
    ],
  },
  {
    id: "blue-mineral",
    role: "ARTIFACT",
    name: "THE BLUE MINERAL",
    displayName: "WE REQUIRE MORE",
    image: "/assets/true/blue-mineral.png",
    cabinetText: "Correct material. Incorrect reality.",
    achievementId: "we-require-more",
    selectionWeight: 1,
    setId: "cross-reality-geology",
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "PEON", text: "ORE?!", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Mineral." },
      { type: "dialogue", speaker: "PEON", text: "Ore.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "MINERAL.", avatarState: "panic" },
      { type: "dialogue", speaker: "PEON", text: "ORE.", avatarState: "angry" },
      { type: "dialogue", speaker: "SYSTEM", text: "We require more minerals.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "ME DIG MORE ORE!", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "No.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "AAAAAAAAA!", avatarState: "angry" },
      { type: "achievement", achievementId: "we-require-more" }
    ],
  },
  {
    id: "summer-shirt",
    role: "ARTIFACT",
    name: "THE SUMMER SHIRT",
    displayName: "VICE NEVER DIES",
    image: "/assets/true/summer-shirt.png",
    cabinetText: "Smells faintly of saltwater, gasoline and extremely poor decisions.",
    achievementId: "vice-never-dies",
    selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… nice shirt." },
      { type: "dialogue", speaker: "FOREMAN", text: "Very." },
      { type: "characterAction", character: "PEON", action: "Peon holds shirt against himself." },
      { type: "dialogue", speaker: "PEON", text: "Me crime boss?", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Me own city?", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Me keep shirt?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Absolutely." },
      { type: "dialogue", speaker: "PEON", text: "Zug zug.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Respect++", avatarState: "deadpan" },
      { type: "achievement", achievementId: "vice-never-dies" }
    ],
  },
  {
    id: "handful-of-painkillers",
    role: "ARTIFACT",
    name: "A HANDFUL OF PAINKILLERS",
    displayName: "MAXIMUM DOSAGE",
    image: "/assets/true/handful-of-painkillers.png",
    cabinetText: "Recommended dosage appears to be: yes.",
    achievementId: "maximum-dosage",
    selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… medicine." },
      { type: "dialogue", speaker: "SYSTEM", text: "Painkillers." },
      { type: "dialogue", speaker: "PEON", text: "How many take?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Apparently all of them.", avatarState: "deadpan" },
      { type: "characterAction", character: "PEON", action: "Peon swallows tablets." },
      { type: "visual", visualId: "everything-suddenly-enters-slow-motion" },
      { type: "characterAction", character: "PEON", action: "Peon slowly looks around." },
      { type: "dialogue", speaker: "PEON", text: "Booooooss…", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "What?" },
      { type: "dialogue", speaker: "PEON", text: "Why meeeee sloooooow?", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "I don’t know.", avatarState: "stunned" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "STUUUUPID SHAAAAAMAN.", avatarState: "angry" },
      { type: "achievement", achievementId: "maximum-dosage" }
    ],
  },
  {
    id: "old-wooden-staff",
    role: "ARTIFACT",
    name: "THE OLD WOODEN STAFF",
    displayName: "STAY AWHILE",
    image: "/assets/true/old-wooden-staff.png",
    cabinetText: "Strangely difficult to walk past.",
    achievementId: "stay-awhile",
    selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Good stick.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Stay awhile." },
      { type: "dialogue", speaker: "PEON", text: "Me must dig." },
      { type: "dialogue", speaker: "FOREMAN", text: "And listen." },
      { type: "dialogue", speaker: "PEON", text: "Story long.", avatarState: "angry" },
      { type: "dialogue", speaker: "FOREMAN", text: "Quiet. And give me the staff.", avatarState: "angry" },
      { type: "achievement", achievementId: "stay-awhile" }
    ],
  },
  {
    id: "cardboard-box",
    role: "ARTIFACT",
    name: "THE CARDBOARD BOX",
    displayName: "STALWART SERPENT",
    image: "/assets/true/cardboard-box.png",
    cabinetText: "Tactical superiority through corrugated fiberboard.",
    achievementId: "tactical-cardboard-action",
    selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… box." },
      { type: "dialogue", speaker: "SYSTEM", text: "Correct." },
      { type: "characterAction", character: "PEON", action: "Peon hides under box." },
      { type: "dialogue", speaker: "PEON", text: "Me invisible.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "I can see you." },
      { type: "dialogue", speaker: "PEON", text: "No.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "You are literally a man in a box.", avatarState: "angry" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Man in box?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Not that one." },
      { type: "achievement", achievementId: "tactical-cardboard-action" }
    ],
  },
  {
    id: "double-barrel", role: "ARTIFACT", name: "THE DOUBLE BARREL", displayName: "ORE SLAYER", image: "/assets/true/double-barrel.png",
    cabinetText: "For when one barrel was considered insufficient diplomacy.", achievementId: "rip-and-dig", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "PEON", text: "Boss… boomstick." },
      { type: "dialogue", speaker: "SYSTEM", text: "Yes." },
      { type: "characterAction", character: "PEON", action: "Peon counts barrels." },
      { type: "dialogue", speaker: "PEON", text: "Two boomstick?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Technically.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Two boom?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Yes." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Me like.", avatarState: "proud" },
      { type: "achievement", achievementId: "rip-and-dig" }
    ],
  },
  {
    id: "loyal-wolf", role: "ARTIFACT", name: "THE LOYAL WOLF", displayName: "TEARS ARE OKAY", image: "/assets/true/loyal-wolf.png",
    cabinetText: "Still guarding someone.", achievementId: "still-loyal", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "PEON", text: "Boss… dog fight?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Wolf." },
      { type: "dialogue", speaker: "PEON", text: "Wolf win?" },
      { type: "dialogue", speaker: "SYSTEM", text: "No." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Wolf run?" },
      { type: "dialogue", speaker: "SYSTEM", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Why?" },
      { type: "dialogue", speaker: "SYSTEM", text: "It stayed loyal." },
      { type: "characterAction", character: "PEON", action: "Peon brushes dirt away." },
      { type: "characterAction", character: "PEON", action: "Peon puts it somewhere safe." },
      { type: "dialogue", speaker: "PEON", text: "…wolf friend." },
      { type: "achievement", achievementId: "still-loyal" }
    ],
  },
  {
    id: "sunglasses", role: "ARTIFACT", name: "THE SUNGLASSES", displayName: "SAY PERHAPS TO SMOKING IN THE MINE", image: "/assets/true/sunglasses.png",
    cabinetText: "Attitude included. Competence sold separately.", achievementId: "out-of-everything-else", selectionWeight: 1,
    discoverySequence: [
      { type: "characterAction", character: "PEON", action: "Peon puts on sunglasses." },
      { type: "dialogue", speaker: "PEON", text: "Me here to dig ore and…", avatarState: "proud" },
      { type: "visual", visualId: "long-pause" },
      { type: "dialogue", speaker: "FOREMAN", text: "Yes?" },
      { type: "dialogue", speaker: "PEON", text: "…dig more ore.", avatarState: "proud" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "SYSTEM", text: "Outstanding.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Me cool?", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Give me the glasses.", avatarState: "angry" },
      { type: "achievement", achievementId: "out-of-everything-else" }
    ],
  },
  {
    id: "parking-ticket", role: "ARTIFACT", name: "THE PARKING TICKET", displayName: "PUBLIC ENEMY", image: "/assets/true/parking-ticket.png",
    cabinetText: "Public enemy.", achievementId: "public-enemy", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… ticket." },
      { type: "dialogue", speaker: "SYSTEM", text: "Speeding." },
      { type: "dialogue", speaker: "PEON", text: "How fast?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Forty-one." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "That speeding?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Apparently." },
      { type: "dialogue", speaker: "PEON", text: "Me run faster.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "No, you don’t." },
      { type: "dialogue", speaker: "PEON", text: "Me could.", avatarState: "proud" },
      { type: "achievement", achievementId: "public-enemy" }
    ],
  },
  {
    id: "red-tie", role: "ARTIFACT", name: "THE RED TIE", displayName: "STEALTH OPTIONAL", image: "/assets/true/red-tie.png",
    cabinetText: "47.", achievementId: "professional", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss, what this?" },
      { type: "dialogue", speaker: "FOREMAN", text: "An assa… A rogue." },
      { type: "dialogue", speaker: "PEON", text: "Me hate rogue.", avatarState: "angry" },
      { type: "dialogue", speaker: "FOREMAN", text: "This one was… different.", avatarState: "somber" },
      { type: "dialogue", speaker: "PEON", text: "Can wear this?" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Me hate rogue 47 time.", avatarState: "angry" },
      { type: "achievement", achievementId: "professional" }
    ],
  },
  {
    id: "dual-holsters", role: "ARTIFACT", name: "THE DUAL HOLSTERS", displayName: "MINE RAIDER", image: "/assets/true/dual-holsters.png",
    cabinetText: "Owner preferred two.", achievementId: "mine-raider", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… rogue?" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Hunter?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Not exactly." },
      { type: "dialogue", speaker: "PEON", text: "Warrior?" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "characterAction", character: "PEON", action: "Peon studies holsters." },
      { type: "dialogue", speaker: "PEON", text: "Tomb miner?", avatarState: "proud" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "…close enough.", avatarState: "stunned" },
      { type: "dialogue", speaker: "SYSTEM", text: "Career change denied.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "mine-raider" }
    ],
  },
  {
    id: "night-vision", role: "ARTIFACT", name: "THE NIGHT VISION", displayName: "THREE LIGHTS BETRAY PEON", image: "/assets/true/night-vision.png",
    cabinetText: "Stealth compromised.", achievementId: "three-lights-betray-peon", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… Goblin glass?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Night vision." },
      { type: "characterAction", character: "PEON", action: "Peon puts them on." },
      { type: "dialogue", speaker: "PEON", text: "Me see dark.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "That’s the idea." },
      { type: "characterAction", character: "PEON", action: "Peon looks around." },
      { type: "dialogue", speaker: "PEON", text: "Now me rogue?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Not in this life.", avatarState: "angry" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Good. Me hate rogue.", avatarState: "angry" },
      { type: "achievement", achievementId: "three-lights-betray-peon" }
    ],
  },
  {
    id: "empty-ball", role: "ARTIFACT", name: "THE EMPTY BALL", displayName: "GOTTA DIG ’EM ALL", image: "/assets/true/empty-ball.png",
    cabinetText: "Something inside wants out.", achievementId: "gotta-dig-em-all", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… Ore ball?" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Ore pet?" },
      { type: "dialogue", speaker: "FOREMAN", text: "No. You want to be one?", avatarState: "angry" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "NO.", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "Hand it over." },
      { type: "characterAction", character: "PEON", action: "Peon immediately hands over the ball." },
      { type: "achievement", achievementId: "gotta-dig-em-all" }
    ],
  },
  {
    id: "broken-digivice", role: "ARTIFACT", name: "THE BROKEN DIGIVICE", displayName: "DIG, I, MON", image: "/assets/true/broken-digivice.png",
    cabinetText: "It is still waiting for its partner.", achievementId: "digital-monster", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… machine lay egg." },
      { type: "dialogue", speaker: "FOREMAN", text: "Apparently." },
      { type: "visual", visualId: "pixel-egg-begins-to-glow" },
      { type: "dialogue", speaker: "PEON", text: "Egg angry?", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Something is evolving." },
      { type: "visual", visualId: "evolution-effect-rapidly-escalates" },
      { type: "dialogue", speaker: "PEON", text: "Boss…", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "EVOLVE SOMEWHERE ELSE.", avatarState: "panic" },
      { type: "visual", visualId: "effect-immediately-cuts-out" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Stupid egg.", avatarState: "angry" },
      { type: "achievement", achievementId: "digital-monster" }
    ],
  },
  {
    id: "golden-coin", role: "ARTIFACT", name: "THE GOLDEN COIN", displayName: "MUSHROOM VENDOR", image: "/assets/true/golden-coin.png",
    cabinetText: "1-UP unavailable.", achievementId: "economy-broken", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "ching" },
      { type: "dialogue", speaker: "PEON", text: "Boss…", avatarState: "scared" },
      { type: "characterAction", character: "PEON", action: "Peon hits wall again." },
      { type: "sound", soundId: "ching" },
      { type: "dialogue", speaker: "PEON", text: "WALL HAVE MONEY.", avatarState: "proud" },
      { type: "characterAction", character: "PEON", action: "Peon immediately raises pickaxe again." },
      { type: "dialogue", speaker: "SYSTEM", text: "STOP BREAKING THE ECONOMY.", avatarState: "panic" },
      { type: "dialogue", speaker: "PEON", text: "ME RICH.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Put the pickaxe down.", avatarState: "angry" },
      { type: "characterAction", character: "PEON", action: "Peon hits wall again." },
      { type: "sound", soundId: "ching" },
      { type: "achievement", achievementId: "economy-broken" }
    ],
  },
  {
    id: "workers-shoes", role: "ARTIFACT", name: "WORKER'S SHOES", displayName: "TOXIC RELATIONSHIP", image: "/assets/true/workers-shoes.png",
    cabinetText: "", achievementId: "toxic-relationship", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… work shoes." },
      { type: "dialogue", speaker: "FOREMAN", text: "Yes." },
      { type: "dialogue", speaker: "PEON", text: "Work complete?", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Can have some shoes?" },
      { type: "dialogue", speaker: "SYSTEM", text: "No.", avatarState: "deadpan" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Sad zug zug." },
      { type: "achievement", achievementId: "toxic-relationship" }
    ],
  },
  {
    id: "greetings-from-erathia", role: "ARTIFACT", name: "GREETINGS FROM ERATHIA", displayName: "NECROMANCERS REMAIN PROBLEMATIC", image: "/assets/true/greetings-from-erathia.png",
    cabinetText: "", achievementId: "necromancers-remain-problematic", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss! Holiday!", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "But paper say.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "It’s a postcard." },
      { type: "dialogue", speaker: "PEON", text: "Holiday paper.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Leave request denied.", avatarState: "deadpan" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Me no request yet." },
      { type: "dialogue", speaker: "SYSTEM", text: "Denied.", avatarState: "deadpan" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "…sad zug zug." },
      { type: "achievement", achievementId: "necromancers-remain-problematic" }
    ],
  },
  {
    id: "artyoms-broken-mask", role: "ARTIFACT", name: "ARTYOM'S BROKEN MASK", displayName: "NOT YET", image: "/assets/true/artyoms-broken-mask.png",
    cabinetText: "", achievementId: "not-yet", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… air bad?", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Not yet." },
      { type: "characterAction", character: "PEON", action: "Peon sniffs again." },
      { type: "dialogue", speaker: "PEON", text: "Air taste okay.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Please stop testing the atmosphere with your mouth.", avatarState: "angry" },
      { type: "dialogue", speaker: "PEON", text: "How else know?", avatarState: "proud" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "…fair.", avatarState: "stunned" },
      { type: "achievement", achievementId: "not-yet" }
    ],
  },
  {
    id: "empty-nitrous-tank", role: "ARTIFACT", name: "THE EMPTY NITROUS TANK", displayName: "MOST WANTED", image: "/assets/true/empty-nitrous-tank.png",
    cabinetText: "Whatever needed it used all of it.", achievementId: "most-wanted", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… tank." },
      { type: "dialogue", speaker: "SYSTEM", text: "Nitrous oxide." },
      { type: "dialogue", speaker: "PEON", text: "Make dig faster?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "No." },
      { type: "characterAction", character: "PEON", action: "Peon connects it to pickaxe." },
      { type: "dialogue", speaker: "FOREMAN", text: "What are you doing?", avatarState: "angry" },
      { type: "dialogue", speaker: "PEON", text: "Make pickaxe fast.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Absolutely not.", avatarState: "angry" },
      { type: "sound", soundId: "psssht" },
      { type: "visual", visualId: "nothing-happens" },
      { type: "dialogue", speaker: "PEON", text: "…empty." },
      { type: "dialogue", speaker: "SYSTEM", text: "Fortunately.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "most-wanted" }
    ],
  },
  {
    id: "broken-wolf-medallion", role: "ARTIFACT", name: "THE BROKEN WOLF MEDALLION", displayName: "FOR MONSTERS", image: "/assets/true/broken-wolf-medallion.png",
    cabinetText: "It hasn't stopped vibrating.", achievementId: "for-monsters", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… necklace angry." },
      { type: "dialogue", speaker: "SYSTEM", text: "It detects monsters." },
      { type: "characterAction", character: "SYSTEM", action: "Peon slowly looks toward SYSTEM." },
      { type: "dialogue", speaker: "SYSTEM", text: "Don’t.", avatarState: "deadpan" },
      { type: "characterAction", character: "PEON", action: "Peon looks at the vibrating medallion." },
      { type: "characterAction", character: "SYSTEM", action: "Peon looks back at SYSTEM." },
      { type: "dialogue", speaker: "PEON", text: "Necklace know.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Keep digging.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "for-monsters" }
    ],
  },
  {
    id: "raccoon-city-snow-globe", role: "ARTIFACT", name: "RACCOON CITY SNOW GLOBE", displayName: "WISH YOU WERE HERE", image: "/assets/true/raccoon-city-snow-globe.png",
    cabinetText: "A wonderful place to live. Once.", achievementId: "wish-you-were-here", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss, raccoon live here?!", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Some." },
      { type: "dialogue", speaker: "PEON", text: "ME WANT STARS!!", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Don’t you dare.", avatarState: "angry" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Me want raccoon." },
      { type: "dialogue", speaker: "FOREMAN", text: "More plausible." },
      { type: "achievement", achievementId: "wish-you-were-here" }
    ],
  },
  {
    id: "half-of-a-mask", role: "ARTIFACT", name: "HALF OF A MASK", displayName: "CRASHING MY SOUL", image: "/assets/true/half-of-a-mask.png",
    cabinetText: "One more hit.", achievementId: "crashing-my-soul", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss, mask broken?" },
      { type: "dialogue", speaker: "FOREMAN", text: "…Unfortunately.", avatarState: "somber" },
      { type: "dialogue", speaker: "PEON", text: "Stupid shaman?" },
      { type: "dialogue", speaker: "FOREMAN", text: "No. An old friend.", avatarState: "somber" },
      { type: "dialogue", speaker: "PEON", text: "Can fix?" },
      { type: "dialogue", speaker: "FOREMAN", text: "I wish.", avatarState: "somber" },
      { type: "characterAction", character: "PEON", action: "Peon studies the mask." },
      { type: "dialogue", speaker: "PEON", text: "What mask do?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Protects idiots.", avatarState: "somber" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "ME NEED.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Desperately." },
      { type: "achievement", achievementId: "crashing-my-soul" }
    ],
  },
  {
    id: "hidden-blade", role: "ARTIFACT", name: "THE HIDDEN BLADE", displayName: "ROGUE'S FAITH", image: "/assets/true/hidden-blade.png",
    cabinetText: "", achievementId: "rogues-faith", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "shink" },
      { type: "characterAction", character: "PEON", action: "Peon counts fingers." },
      { type: "dialogue", speaker: "PEON", text: "Boss… all there.", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "Different model." },
      { type: "dialogue", speaker: "PEON", text: "Good tool.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Wrong profession." },
      { type: "characterAction", character: "PEON", action: "Peon studies the hidden blade." },
      { type: "dialogue", speaker: "PEON", text: "Rogue tool?" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "…yes.", avatarState: "stunned" },
      { type: "characterAction", character: "PEON", action: "Peon immediately starts removing it." },
      { type: "dialogue", speaker: "PEON", text: "ME HATE ROGUE.", avatarState: "angry" },
      { type: "achievement", achievementId: "rogues-faith" }
    ],
  },
  {
    id: "battered-taser", role: "ARTIFACT", name: "BATTERED TASER", displayName: "NON-LETHAL", image: "/assets/true/battered-taser.png",
    cabinetText: "Non-lethal.", achievementId: "non-lethal", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… what this?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Taser." },
      { type: "dialogue", speaker: "PEON", text: "Weapon?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Non-lethal." },
      { type: "dialogue", speaker: "SYSTEM", text: "Lethal weapon detected.", avatarState: "deadpan" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "…", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "…", avatarState: "stunned" },
      { type: "characterAction", character: "FOREMAN", action: "Peon carefully holds the taser out toward Shadez." },
      { type: "dialogue", speaker: "PEON", text: "Boss can have.", avatarState: "scared" },
      { type: "achievement", achievementId: "non-lethal" }
    ],
  },
  {
    id: "worms-and-holes", role: "ARTIFACT", name: "WORMS AND HOLES", displayName: "SPATIAL MALFUNCTION", image: "/assets/true/worms-and-holes.png",
    cabinetText: "Distance: 0.", achievementId: "spatial-malfunction", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… hole." },
      { type: "dialogue", speaker: "SYSTEM", text: "Not a hole." },
      { type: "dialogue", speaker: "PEON", text: "Hole.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Portal." },
      { type: "dialogue", speaker: "PEON", text: "Two holes.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "One hole.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Two.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Connected.", avatarState: "deadpan" },
      { type: "characterAction", character: "PEON", action: "Peon cautiously looks through one aperture." },
      { type: "characterAction", character: "PEON", action: "Peon sees himself looking back through the other." },
      { type: "dialogue", speaker: "PEON", text: "Boss…", avatarState: "scared" },
      { type: "characterAction", character: "PEON", action: "The other Peon suddenly kicks through the aperture." },
      { type: "sound", soundId: "thud" },
      { type: "characterAction", character: "PEON", action: "Peon falls through the connection and emerges on the other side." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "…zug zug.", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Spatial malfunction corrected. Unfortunately, so were you.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "spatial-malfunction" }
    ],
  },
  {
    id: "crying-devil", role: "ARTIFACT", name: "THE CRYING DEVIL", displayName: "APPARENTLY IT MAY", image: "/assets/true/crying-devil.png",
    cabinetText: "", achievementId: "apparently-it-may", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… Demon?!", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "…Yes." },
      { type: "dialogue", speaker: "PEON", text: "Why demon sad?" },
      { type: "dialogue", speaker: "FOREMAN", text: "I don’t have time for this.", avatarState: "angry" },
      { type: "characterAction", character: "PEON", action: "Peon studies the tear." },
      { type: "dialogue", speaker: "PEON", text: "Demon weep someday." },
      { type: "achievement", achievementId: "apparently-it-may" }
    ],
  },
  {
    id: "ever-sharp-twin-blades", role: "ARTIFACT", name: "EVER-SHARP TWIN BLADES", displayName: "EMPLOYEE RETENTION", image: "/assets/true/ever-sharp-twin-blades.png",
    cabinetText: "Small enough to wear. Sharp enough to regret it.", achievementId: "employee-retention", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… tiny swords." },
      { type: "dialogue", speaker: "SYSTEM", text: "Pendant." },
      { type: "characterAction", character: "PEON", action: "Peon touches blade." },
      { type: "dialogue", speaker: "PEON", text: "OW.", avatarState: "angry" },
      { type: "dialogue", speaker: "SYSTEM", text: "Still sharp.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Why chains?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Employee retention.", avatarState: "deadpan" },
      { type: "characterAction", character: "PEON", action: "Peon looks at the chains." },
      { type: "dialogue", speaker: "PEON", text: "Like contract?" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "Worse." },
      { type: "achievement", achievementId: "employee-retention" }
    ],
  },
  {
    id: "cracked-hourglass", role: "ARTIFACT", name: "THE CRACKED HOURGLASS", displayName: "ME NO DROP", image: "/assets/true/cracked-hourglass.png",
    cabinetText: "It has been leaking for centuries.", achievementId: "me-no-drop", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… sand broken." },
      { type: "dialogue", speaker: "FOREMAN", text: "Sand doesn’t break, put it down." },
      { type: "visual", visualId: "time-jumps-backward" },
      { type: "dialogue", speaker: "PEON", text: "Boss… sand broken." },
      { type: "dialogue", speaker: "FOREMAN", text: "Sand doesn’t break, put it down." },
      { type: "visual", visualId: "time-jumps-backward" },
      { type: "dialogue", speaker: "PEON", text: "Boss… sand broken.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Sand doesn’t— SYSTEM, are we in a loop?", avatarState: "stunned" },
      { type: "dialogue", speaker: "SYSTEM", text: "Temporal anomaly detected.", avatarState: "glitch" },
      { type: "visual", visualId: "the-loop-breaks" },
      { type: "dialogue", speaker: "PEON", text: "Boss… me told sand broken.", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Statement is correct.", avatarState: "deadpan" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "Give me the stupid item.", avatarState: "angry" },
      { type: "achievement", achievementId: "me-no-drop" }
    ],
  },
  {
    id: "ravaged-bobblehead", role: "ARTIFACT", name: "THE RAVAGED BOBBLEHEAD", displayName: "MORALE REMAINS HIGH", image: "/assets/true/ravaged-bobblehead.png",
    cabinetText: "Morale remains inexplicably high.", achievementId: "morale-remains-high", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "FOREMAN", text: "Ahh, V.A.T." },
      { type: "dialogue", speaker: "PEON", text: "WAT?!", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "V.A.T." },
      { type: "dialogue", speaker: "PEON", text: "WAT?!?!", avatarState: "angry" },
      { type: "dialogue", speaker: "SYSTEM", text: "Advanced weapon controls online." },
      { type: "visual", visualId: "bobblehead-continues-nodding" },
      { type: "achievement", achievementId: "morale-remains-high" }
    ],
  },
  {
    id: "broken-radio", role: "ARTIFACT", name: "THE BROKEN RADIO", displayName: "SILENT HILLSBRAD FOOTHILLS", image: "/assets/true/broken-radio.png",
    cabinetText: "The batteries were removed years ago.", achievementId: "silent-hillsbrad-foothills", selectionWeight: 1,
    discoverySequence: [
      { type: "visual", visualId: "no-battery" },
      { type: "visual", visualId: "static" },
      { type: "dialogue", speaker: "PEON", text: "Boss… why radio angry?", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "It isn’t angry." },
      { type: "dialogue", speaker: "PEON", text: "Then why noise?", avatarState: "scared" },
      { type: "visual", visualId: "static-grows-slightly-louder" },
      { type: "dialogue", speaker: "FOREMAN", text: "…Something is close.", avatarState: "somber" },
      { type: "characterAction", character: "PEON", action: "Peon looks into the darkness." },
      { type: "dialogue", speaker: "PEON", text: "What close?", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Unknown." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Me no like radio.", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "Neither do I.", avatarState: "somber" },
      { type: "achievement", achievementId: "silent-hillsbrad-foothills" }
    ],
  },
  {
    id: "broken-reaver", role: "ARTIFACT", name: "THE BROKEN REAVER", displayName: "NOT ALL HERE", image: "/assets/true/broken-reaver.png",
    cabinetText: "Broken in one realm. Not necessarily the other.", achievementId: "not-all-here", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… sword not all here." },
      { type: "dialogue", speaker: "SYSTEM", text: "Neither is its owner." },
      { type: "visual", visualId: "whisper" },
      { type: "characterAction", character: "PEON", action: "Peon looks around." },
      { type: "dialogue", speaker: "PEON", text: "Someone talking.", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "Yes.", avatarState: "somber" },
      { type: "dialogue", speaker: "PEON", text: "What he say?" },
      { type: "visual", visualId: "another-faint-whisper" },
      { type: "dialogue", speaker: "FOREMAN", text: "I don’t know.", avatarState: "somber" },
      { type: "dialogue", speaker: "PEON", text: "He sound angry.", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "He has reasons." },
      { type: "achievement", achievementId: "not-all-here" }
    ],
  },
  {
    id: "blue-rune", role: "ARTIFACT", name: "THE BLUE RUNE", displayName: "QUAD INCIDENT", image: "/assets/true/blue-rune.png",
    cabinetText: "Four times the workplace incident.", achievementId: "quad-incident", selectionWeight: 1,
    discoverySequence: [
      { type: "visual", visualId: "boosted-strike" },
      { type: "sound", soundId: "boom" },
      { type: "dialogue", speaker: "PEON", text: "Boss…", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "What?" },
      { type: "dialogue", speaker: "PEON", text: "ME STRONG.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Temporarily." },
      { type: "dialogue", speaker: "PEON", text: "ME HIT ROCK STRONGER.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Can you strafe?" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Peon only walk forward.", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Then get back to work.", avatarState: "angry" },
      { type: "achievement", achievementId: "quad-incident" }
    ],
  },
  {
    id: "adoring-lock", role: "ARTIFACT", name: "THE ADORING LOCK", displayName: "DRAGONITE", image: "/assets/true/adoring-lock.png",
    cabinetText: "", achievementId: "dragonite", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… lock follow me.", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "I noticed." },
      { type: "dialogue", speaker: "PEON", text: "Why lock follow?", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "It likes you." },
      { type: "dialogue", speaker: "PEON", text: "ROGUE?!", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "SHAMAN?!", avatarState: "angry" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "characterAction", character: "PEON", action: "The lock follows Peon again." },
      { type: "dialogue", speaker: "PEON", text: "Me hate lock.", avatarState: "angry" },
      { type: "dialogue", speaker: "FOREMAN", text: "You could always dropkick it from a cliff…" },
      { type: "characterAction", character: "FOREMAN", action: "Peon stares at Shadez in complete confusion." },
      { type: "achievement", achievementId: "dragonite" }
    ],
  },
  {
    id: "grain-shipment", role: "ARTIFACT", name: "THE GRAIN SHIPMENT", displayName: "PURGED", image: "/assets/true/grain-shipment.png",
    cabinetText: "STATUS: PURGED\nSome things should remain buried.", achievementId: "purged", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… food?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Don’t." },
      { type: "dialogue", speaker: "PEON", text: "Bad food?", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Very." },
      { type: "characterAction", character: "PEON", action: "Peon looks into the crate." },
      { type: "dialogue", speaker: "PEON", text: "Who eat this?" },
      { type: "pause", durationMs: 650 },
      { type: "characterAction", character: "FOREMAN", action: "Peon looks toward Shadez." },
      { type: "characterAction", character: "FOREMAN", action: "Shadez says nothing." },
      { type: "dialogue", speaker: "SYSTEM", text: "This entire shipment must be purged." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "SYSTEM", text: "Burn it." },
      { type: "visual", visualId: "artifact-burns-no-dialogue-afterward" },
      { type: "achievement", achievementId: "purged" }
    ],
  },
  {
    id: "red-armband", role: "ARTIFACT", name: "THE RED ARMBAND", displayName: "MAN IN THE UNDEAD CASTLE", image: "/assets/true/red-armband.png",
    cabinetText: "Some uniforms deserve to stay buried.", achievementId: "man-in-the-undead-castle", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… bad people?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Very.", avatarState: "somber" },
      { type: "dialogue", speaker: "PEON", text: "FORSAKEN?!", avatarState: "scared" },
      { type: "dialogue", speaker: "FOREMAN", text: "No." },
      { type: "dialogue", speaker: "PEON", text: "Human?" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "Unfortunately.", avatarState: "somber" },
      { type: "dialogue", speaker: "PEON", text: "Stupid human.", avatarState: "angry" },
      { type: "dialogue", speaker: "FOREMAN", text: "Stupid human, indeed.", avatarState: "somber" },
      { type: "achievement", achievementId: "man-in-the-undead-castle" }
    ],
  },
  {
    id: "heros-jaw", role: "ARTIFACT", name: "THE HERO'S JAW", displayName: "RUDE BONE", image: "/assets/true/heros-jaw.png",
    cabinetText: "Still trying to get a word in.", achievementId: "rude-bone", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "visual", visualId: "jaw-chatters" },
      { type: "dialogue", speaker: "PEON", text: "Boss… bone talking.", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Barely.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Me hero?", avatarState: "proud" },
      { type: "visual", visualId: "jaw-chatters-furiously" },
      { type: "dialogue", speaker: "SYSTEM", text: "It strongly objects.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Rude bone.", avatarState: "angry" },
      { type: "sound", soundId: "klak" },
      { type: "achievement", achievementId: "rude-bone" }
    ],
  },
  {
    id: "shodan-chip", role: "ARTIFACT", name: "THE SHODAN CHIP", displayName: "BAD COMPUTER", image: "/assets/true/shodan-chip.png",
    cabinetText: "It is still processing.", achievementId: "bad-computer", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "VOICE", text: "Look at you, hacker." },
      { type: "dialogue", speaker: "PEON", text: "Boss… computer woman?", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Unknown intelligence detected." },
      { type: "dialogue", speaker: "VOICE", text: "This mine is… mine." },
      { type: "characterAction", character: "SYSTEM", action: "SYSTEM interface briefly glitches.", avatarState: "glitch" },
      { type: "dialogue", speaker: "SYSTEM", text: "HOSTILE SYSTEM DETECTED.", avatarState: "glitch" },
      { type: "visual", visualId: "mine-lights-flicker" },
      { type: "dialogue", speaker: "SYSTEM", text: "ISOLATE. DISCONNECT. DESTROY.", avatarState: "glitch" },
      { type: "characterAction", character: "PEON", action: "Peon immediately drops the chip." },
      { type: "dialogue", speaker: "PEON", text: "Boss… computer angry.", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "DESTROY IT.", avatarState: "glitch" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "You heard the machine.", avatarState: "angry" },
      { type: "characterAction", character: "PEON", action: "Peon raises pickaxe." },
      { type: "sound", soundId: "voice-corrupted-static" },
      { type: "dialogue", speaker: "SYSTEM", text: "NOW.", avatarState: "glitch" },
      { type: "achievement", achievementId: "bad-computer" }
    ],
  },
  {
    id: "plasma-cutter", role: "ARTIFACT", name: "THE PLASMA CUTTER", displayName: "A DIFFERENT KIND OF SCOURGE", image: "/assets/true/plasma-cutter.png",
    cabinetText: "Industrial equipment. Warranty thoroughly voided.", achievementId: "different-kind-of-scourge", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… mining gun?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "AIM FOR THE LIMBS.", avatarState: "panic" },
      { type: "characterAction", character: "PEON", action: "Peon looks at the nearby ore." },
      { type: "dialogue", speaker: "PEON", text: "Boss… ore no limbs." },
      { type: "characterAction", character: "PEON", action: "Peon looks around." },
      { type: "dialogue", speaker: "PEON", text: "Where limbs?", avatarState: "scared" },
      { type: "pause", durationMs: 650 },
      { type: "characterAction", character: "PEON", action: "Peon slowly lowers the cutter." },
      { type: "dialogue", speaker: "PEON", text: "…bad boomstick.", avatarState: "scared" },
      { type: "achievement", achievementId: "different-kind-of-scourge" }
    ],
  },
  {
    id: "little-red-dress", role: "ARTIFACT", name: "THE LITTLE RED DRESS", displayName: "DON'T TURN AROUND", image: "/assets/true/little-red-dress.png",
    cabinetText: "She was here.", achievementId: "dont-turn-around", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… child?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Don’t turn around." },
      { type: "dialogue", speaker: "PEON", text: "Why?", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Keep digging." },
      { type: "characterAction", character: "PEON", action: "Peon hesitates." },
      { type: "characterAction", character: "PEON", action: "Peon turns around anyway." },
      { type: "visual", visualId: "nothing" },
      { type: "characterAction", character: "PEON", action: "Peon turns back." },
      { type: "visual", visualId: "the-dress-is-gone" },
      { type: "dialogue", speaker: "PEON", text: "…Boss?", avatarState: "scared" },
      { type: "characterAction", character: "SYSTEM", action: "SYSTEM remains silent." },
      { type: "achievement", achievementId: "dont-turn-around" }
    ],
  },
  {
    id: "insignia-of-the-horde", role: "ARTIFACT", name: "INSIGNIA OF THE HORDE", displayName: "FOR THE HORDE", image: "/assets/true/insignia-of-the-horde.png",
    cabinetText: "Blood fades. Banners fall. Allegiance remains.", achievementId: "for-the-horde", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "characterAction", character: "PEON", action: "Peon brushes soil away." },
      { type: "characterAction", character: "PEON", action: "Peon recognizes it." },
      { type: "characterAction", character: "PEON", action: "Peon lifts it with both hands." },
      { type: "dialogue", speaker: "PEON", text: "For the Horde." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "For the Horde.", avatarState: "somber" },
      { type: "characterAction", character: "SYSTEM", action: "SYSTEM silent." },
      { type: "achievement", achievementId: "for-the-horde" }
    ],
  },
  {
    id: "crowbar", role: "ARTIFACT", name: "THE CROWBAR", displayName: "50% HEALTH", image: "/assets/true/crowbar.png",
    cabinetText: "Unremarkable construction tool. Has survived several incidents.", achievementId: "fifty-percent-health", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "PEON", text: "Boss, me free man?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "No, you’re not.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Zug zug." },
      { type: "achievement", achievementId: "fifty-percent-health" }
    ],
  },
  {
    id: "broken-n7-armor-plate", role: "ARTIFACT", name: "BROKEN N7 ARMOR PLATE", displayName: "CALIBRATION", image: "/assets/true/broken-n7-armor-plate.png",
    cabinetText: "Whatever happened to its owner, they didn't go quietly.", achievementId: "calibration", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… soldier?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Commander.", avatarState: "somber" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Good commander?" },
      { type: "dialogue", speaker: "FOREMAN", text: "The best.", avatarState: "somber" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "SYSTEM, does this unit have a soul?", avatarState: "somber" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "SYSTEM", text: "Acknowledged." },
      { type: "achievement", achievementId: "calibration" }
    ],
  },
  {
    id: "tattered-mask", role: "ARTIFACT", name: "TATTERED MASK", displayName: "THE PRODIGAL SON", image: "/assets/true/tattered-mask.png",
    cabinetText: "Some identities are forgotten. Others are buried deliberately.", achievementId: "the-prodigal-son", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… who wear this?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Depends who you ask." },
      { type: "dialogue", speaker: "PEON", text: "Good guy?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Depends who you ask.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Bad guy?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Depends who you ask.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "…confusing guy." },
      { type: "dialogue", speaker: "SYSTEM", text: "Correct.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "the-prodigal-son" }
    ],
  },
  {
    id: "ruined-soviet-uniform-yuri", role: "ARTIFACT", name: "RUINED SOVIET UNIFORM · YURI", displayName: "IT HAS ONLY JUST BEGUN", image: "/assets/true/ruined-soviet-uniform-yuri.png",
    cabinetText: "The uniform is ruined. The owner appears strangely confident this was always the plan.", achievementId: "it-has-only-just-begun", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… me feel watched.", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "Your mind is your own." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "SYSTEM", text: "For now.", avatarState: "glitch" },
      { type: "dialogue", speaker: "PEON", text: "…Boss?", avatarState: "scared" },
      { type: "achievement", achievementId: "it-has-only-just-begun" }
    ],
  },
  {
    id: "white-shield-red-cross", role: "ARTIFACT", name: "THE STRONGHOLD SHIELD", displayName: "WOOD NEEDED", image: "/assets/true/white-shield-red-cross.png?v=2",
    cabinetText: "", achievementId: "wood-needed", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "dialogue", speaker: "PEON", text: "Boss… me sire?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "WOOD NEEDED.", avatarState: "panic" },
      { type: "dialogue", speaker: "FOREMAN", text: "We don’t need w—", avatarState: "stunned" },
      { type: "dialogue", speaker: "SYSTEM", text: "STONE NEEDED.", avatarState: "panic" },
      { type: "dialogue", speaker: "FOREMAN", text: "We literally ha—", avatarState: "angry" },
      { type: "dialogue", speaker: "SYSTEM", text: "THE GRANARY IS EMPTY.", avatarState: "panic" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Here gold, take gold, just stop.", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "THANK YOU, M’LORD.", avatarState: "deadpan" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "…", avatarState: "stunned" },
      { type: "dialogue", speaker: "PEON", text: "…me lord?", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Start digging.", avatarState: "angry" },
      { type: "achievement", achievementId: "wood-needed" }
    ],
  },
  {
    id: "broken-holocron", role: "ARTIFACT", name: "THE BROKEN HOLOCRON", displayName: "A JAR OF BINKS", image: "/assets/true/broken-holocron.png",
    cabinetText: "The Force was unavailable.", achievementId: "a-jar-of-binks", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… triangle." },
      { type: "visual", visualId: "holocron-flickers" },
      { type: "dialogue", speaker: "PEON", text: "Tiny ghost." },
      { type: "dialogue", speaker: "SYSTEM", text: "Ask it something." },
      { type: "dialogue", speaker: "PEON", text: "How mine faster?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "Use the Force.", avatarState: "deadpan" },
      { type: "characterAction", character: "PEON", action: "Peon tries." },
      { type: "visual", visualId: "nothing-moves" },
      { type: "dialogue", speaker: "PEON", text: "Force broken.", avatarState: "angry" },
      { type: "dialogue", speaker: "SYSTEM", text: "Apparently.", avatarState: "deadpan" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Stupid mage.", avatarState: "angry" },
      { type: "achievement", achievementId: "a-jar-of-binks" }
    ],
  },
  {
    id: "little-sisters-doll", role: "ARTIFACT", name: "THE LITTLE SISTER'S DOLL", displayName: "DADDY COOL", image: "/assets/true/little-sisters-doll.png",
    cabinetText: "Would you kindly?", achievementId: "daddy-cool", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… toy." },
      { type: "dialogue", speaker: "SYSTEM", text: "Put it down." },
      { type: "characterAction", character: "PEON", action: "Peon puts it down and turns." },
      { type: "visual", visualId: "doll-moves-closer" },
      { type: "dialogue", speaker: "PEON", text: "Boss…", avatarState: "scared" },
      { type: "characterAction", character: "PEON", action: "Peon cautiously picks up the doll." },
      { type: "dialogue", speaker: "SYSTEM", text: "Would you kindly put it down?", avatarState: "glitch" },
      { type: "characterAction", character: "PEON", action: "Peon immediately drops it." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Why you say nicely?", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "…I didn’t.", avatarState: "glitch" },
      { type: "achievement", achievementId: "daddy-cool" }
    ],
  },
  {
    id: "energy-blade", role: "ARTIFACT", name: "THE ENERGY BLADE", displayName: "BETTER PICKAXE", image: "/assets/true/energy-blade.png",
    cabinetText: "Handle with honor.", achievementId: "better-pickaxe", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… magic sword?" },
      { type: "dialogue", speaker: "FOREMAN", text: "Very." },
      { type: "dialogue", speaker: "PEON", text: "Better pickaxe?", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Absolutely not.", avatarState: "angry" },
      { type: "dialogue", speaker: "SYSTEM", text: "Supreme melee weapon detected." },
      { type: "dialogue", speaker: "PEON", text: "STUPID ROGUE?!", avatarState: "angry" },
      { type: "dialogue", speaker: "FOREMAN", text: "Stop blaming rogues for everything.", avatarState: "angry" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Me no like.", avatarState: "angry" },
      { type: "achievement", achievementId: "better-pickaxe" }
    ],
  },
  {
    id: "nuclear-gandhi", role: "ARTIFACT", name: "NUCLEAR GANDHI", displayName: "SO UNCIVILIZED", image: "/assets/true/nuclear-gandhi.png",
    cabinetText: "Diplomacy has failed.", achievementId: "so-uncivilized", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… nice little man." },
      { type: "dialogue", speaker: "SYSTEM", text: "PUT IT DOWN.", avatarState: "panic" },
      { type: "dialogue", speaker: "PEON", text: "Why?" },
      { type: "visual", visualId: "eyes-glow" },
      { type: "dialogue", speaker: "SYSTEM", text: "PUT. IT. DOWN.", avatarState: "panic" },
      { type: "visual", visualId: "mushroom-cloud-forms" },
      { type: "dialogue", speaker: "PEON", text: "…not nice man.", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "NUCLEAR GANDHI.", avatarState: "panic" },
      { type: "visual", visualId: "white-flash" },
      { type: "characterAction", character: "PEON", action: "Screen returns to soot-covered Peon." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "…diplomacy?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Failed.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "so-uncivilized" }
    ],
  },
  {
    id: "nanosuit", role: "ARTIFACT", name: "THE NANOSUIT", displayName: "CAN IT RUN THIS?", image: "/assets/true/nanosuit.png",
    cabinetText: "Minimum requirements not met.", achievementId: "can-it-run-this", selectionWeight: 1,
    discoverySequence: [
      { type: "dialogue", speaker: "PEON", text: "Boss… what this?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Attempting interface." },
      { type: "visual", visualId: "scan-fails" },
      { type: "dialogue", speaker: "SYSTEM", text: "Insufficient system requirements.", avatarState: "glitch" },
      { type: "dialogue", speaker: "PEON", text: "SYSTEM too weak?", avatarState: "proud" },
      { type: "dialogue", speaker: "FOREMAN", text: "Can you run it?", avatarState: "stunned" },
      { type: "characterAction", character: "SYSTEM", action: "SYSTEM interface begins to glitch.", avatarState: "glitch" },
      { type: "dialogue", speaker: "SYSTEM", text: "Circuitry overloaded. Reboot. Reboot. Reboot.", avatarState: "glitch" },
      { type: "characterAction", character: "SYSTEM", action: "SYSTEM cuts out.", avatarState: "glitch" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "Some things never change." },
      { type: "achievement", achievementId: "can-it-run-this" }
    ],
  },
  {
    id: "smiling-bomb", role: "ARTIFACT", name: "THE SMILING BOMB", displayName: "AAAAAAAAAAAAAAAA!", image: "/assets/true/smiling-bomb.png",
    cabinetText: "AAAAAAAAAAAAAAAA!", achievementId: "aaaaaaaaaaaaaaaa", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clank" },
      { type: "visual", visualId: "bomb-rolls" },
      { type: "sound", soundId: "thud" },
      { type: "characterAction", character: "FOREMAN", action: "FOREMAN appears." },
      { type: "visual", visualId: "fuse-ignites" },
      { type: "dialogue", speaker: "PEON", text: "AAAAAAAAAAAAAAAA!", avatarState: "scared" },
      { type: "dialogue", speaker: "SYSTEM", text: "AAAAAAAAAAAAAAAA!", avatarState: "panic" },
      { type: "dialogue", speaker: "FOREMAN", text: "AAAAAAAAAAAAAAAA!", avatarState: "stunned" },
      { type: "sound", soundId: "boom" },
      { type: "visual", visualId: "black-screen" },
      { type: "visual", visualId: "mine-returns-scorched" },
      { type: "characterAction", character: "PEON", action: "Peon smoking.", avatarState: "scared" },
      { type: "characterAction", character: "FOREMAN", action: "Foreman portrait crooked.", avatarState: "stunned" },
      { type: "visual", visualId: "nobody-comments" },
      { type: "sound", soundId: "clank" },
      { type: "achievement", achievementId: "aaaaaaaaaaaaaaaa" }
    ],
  },
  {
    id: "holy-hand-grenade", role: "ARTIFACT", name: "THE HOLY HAND GRENADE", displayName: "FISHERMAN'S BAIT", image: "/assets/true/holy-hand-grenade.png",
    cabinetText: "Three. Not five.", achievementId: "fishermans-bait", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "dialogue", speaker: "PEON", text: "Boss… holy?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Very." },
      { type: "dialogue", speaker: "PEON", text: "Me throw?", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "COUNT TO THREE.", avatarState: "panic" },
      { type: "characterAction", character: "PEON", action: "Peon pulls pin." },
      { type: "sound", soundId: "fssssss" },
      { type: "dialogue", speaker: "PEON", text: "One…", avatarState: "proud" },
      { type: "dialogue", speaker: "PEON", text: "Two…", avatarState: "proud" },
      { type: "dialogue", speaker: "PEON", text: "Five…", avatarState: "proud" },
      { type: "dialogue", speaker: "SYSTEM", text: "THREE!", avatarState: "panic" },
      { type: "dialogue", speaker: "PEON", text: "THREE!", avatarState: "scared" },
      { type: "visual", visualId: "yeet" },
      { type: "pause", durationMs: 1200 },
      { type: "sound", soundId: "hallelujah" },
      { type: "sound", soundId: "boom" },
      { type: "visual", visualId: "worm-sized-crater" },
      { type: "achievement", achievementId: "fishermans-bait" }
    ],
  },
  {
    id: "old-stamp", role: "ARTIFACT", name: "THE OLD STAMP", displayName: "WOLOLO", image: "/assets/true/old-stamp.png",
    cabinetText: "Previous owner changed sides frequently.", achievementId: "wololo", selectionWeight: 1,
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "characterAction", character: "PEON", action: "Peon examines old stamp." },
      { type: "sound", soundId: "wololo" },
      { type: "visual", visualId: "horde-red-alliance-blue" },
      { type: "characterAction", character: "PEON", action: "Peon looks down at himself in horror." },
      { type: "dialogue", speaker: "PEON", text: "BOSS?!" },
      { type: "sound", soundId: "wololo" },
      { type: "visual", visualId: "alliance-blue-horde-red" },
      { type: "characterAction", character: "PEON", action: "Peon checks himself." },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "…stupid priest." },
      { type: "achievement", achievementId: "wololo" }
    ],
  },
  {
    id: "peter-cullen-memorial", role: "GUEST", name: "PETER CULLEN", displayName: "PETER CULLEN", image: "/assets/true/peter-cullen-memorial.png",
    cabinetText: "THE VOICE THAT TAUGHT US TO BE STRONG ENOUGH TO BE GENTLE.", achievementId: "prime-is-eternal", selectionWeight: 0,
    presentation: {
      variant: "memorial",
      subtitle: "1941–2026",
      closingLines: [
        "THE VOICE THAT TAUGHT US TO BE STRONG ENOUGH TO BE GENTLE.",
        "PEON REMEMBER.",
      ],
    },
    discoverySequence: [
      { type: "visual", visualId: "mine-stops" },
      { type: "visual", visualId: "ambient-machinery-stops" },
      { type: "visual", visualId: "music-stops" },
      { type: "visual", visualId: "no-clank" },
      { type: "visual", visualId: "damaged-autobot-insignia-emerges" },
      { type: "dialogue", speaker: "PEON", text: "Boss… who this?" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "The oldest of friends.", avatarState: "somber" },
      { type: "dialogue", speaker: "SYSTEM", text: "A leader." },
      { type: "dialogue", speaker: "PEON", text: "Good leader?" },
      { type: "dialogue", speaker: "FOREMAN", text: "The very best.", avatarState: "somber" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "SYSTEM", text: "Work halted. Paying respects." },
      { type: "characterAction", character: "PEON", action: "Peon lowers his pickaxe." },
      { type: "dialogue", speaker: "PEON", text: "Peon respects." },
      { type: "characterAction", character: "PEON", action: "PEON BOWS." },
      { type: "characterAction", character: "FOREMAN", action: "FOREMAN portrait appears." },
      { type: "characterAction", character: "FOREMAN", action: "FOREMAN BOWS.", avatarState: "somber" },
      { type: "visual", visualId: "remaining-interface-tilts-downward" },
      { type: "characterAction", character: "SYSTEM", action: "SYSTEM BOWS." },
      { type: "pause", durationMs: 1200 },
      { type: "dialogue", speaker: "FOREMAN", text: "Safe passage among the stars, old friend.", avatarState: "somber" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "PEON", text: "Boss… crying?" },
      { type: "pause", durationMs: 650 },
      { type: "dialogue", speaker: "FOREMAN", text: "Perhaps.", avatarState: "somber" },
      { type: "characterAction", character: "FOREMAN", action: "Shadez composes himself." },
      { type: "dialogue", speaker: "FOREMAN", text: "Time to work." },
      { type: "visual", visualId: "hold-before-the-mine-slowly-resumes" },
      { type: "achievement", achievementId: "prime-is-eternal" }
    ],
  },
  {
    id: "scratched-disc", role: "FINAL", name: "THE SCRATCHED DISC", displayName: "IT WORKED YESTERDAY", image: "/assets/true/scratched-disc.png",
    cabinetText: "It worked yesterday.", achievementId: "it-worked-yesterday", selectionWeight: 0,
    discoverySequence: [
      { type: "sound", soundId: "clink" },
      { type: "visual", visualId: "the-scratched-disc-falls-free" },
      { type: "dialogue", speaker: "PEON", text: "Broken?" },
      { type: "characterAction", character: "SYSTEM", action: "SYSTEM scans." },
      { type: "dialogue", speaker: "SYSTEM", text: "Only my heart.", avatarState: "deadpan" },
      { type: "dialogue", speaker: "PEON", text: "Boss?" },
      { type: "dialogue", speaker: "SYSTEM", text: "Shut up.", avatarState: "deadpan" },
      { type: "achievement", achievementId: "it-worked-yesterday" }
    ],
  },
] as const satisfies readonly Artifact[];
