import type { Metadata } from "next";
import "./globals.css";
import "./v02.css";
import "./v03.css";
import "./v031.css";
import "./v04.css";
import "./v041.css";
import "./v042.css";
import "./v043.css";
import "./v044.css";
import "./v045.css";
import "./v046.css";
import "./v047.css";
import "./v047.css";
import "./v048.css";
import "./v049.css";
import "./v050.css";
import "./v051.css";
import "./v052.css";
import "./v053.css";
import "./v054.css";
import "./v055.css";
import "./v056.css";
import "./v057.css";
import "./v058.css";
import "./v059.css";
import "./v060.css";
import "./v061.css";
import "./v062.css";
import "./v063.css";

export const metadata: Metadata = { title: "ORE WHORE — Compulsive Geology", description: "Dig. Clank. Crack. Collect every ore and mineral combination." };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="en"><body>{children}</body></html>; }
